apiVersion: v1
kind: ConfigMap
metadata:
  name: be-config
data:
  DB_HOST: db-service
  DB_PORT: "5432"
  DB_NAME: mydb
  DB_USER: myuser

---

apiVersion: v1
kind: Secret
metadata:
  name: be-sec
data:
  DB_PASS: cGFzc3dvcmQxMjMK    # base64 hashed

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-deploy
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      name: flask-pod
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: mahmoudraslan/flask-backend:1.1
        ports:
        - containerPort: 5000

        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: be-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: be-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: be-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: be-config
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: be-sec
              key: DB_PASS

---

apiVersion: v1
kind: Service
metadata:
  name: be-service
spec: 
  type: ClusterIP
  selector:
    app: flask
  ports:
  - port: 5000
    targetPort: 5000
