apiVersion: v1
kind: ConfigMap
metadata:
  name: fe-nginx-conf
  namespace: demo
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;
        location / {
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_pass http://be-service.demo.svc.cluster.local:5000/;
        }
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: nginx
          image: mahmoudraslan/nginx-frontend:1.1
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-conf
          configMap:
            name: fe-nginx-conf

---
apiVersion: v1
kind: Service
metadata:
  name: fe-service
  namespace: demo
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
